services:
  Plugin\HTMLPurifier\Form\Extension\TextTypeExtension:
    arguments:
      - '@Eccube\Request\Context'
    tags:
      - { name: form.type_extension, priority: -999, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType}
